app: web-proyecto-serverless
org: jeffer24
#console: true

service: serverless-church-module

frameworkVersion: '3'

#plugins:
  #- serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: "us-east-1"
  stage: ${opt:stage}

  apiGateway:
    request:
      schemas:
        church-input-model:
          name: ChurchInputModel
          schema: ${file(infraestructure/handlers/schemas/churches-schema.json)}
          description: "Validacion de los datos de la congregacion"

functions:
  getChurches:
    handler: infraestructure/handlers/churches-handler.getChurches
    events:
      - http:
          path: churches
          method: get
          #cors: true
          #authorizer: aws_iam
  createChurch:
    handler: infraestructure/handlers/churches-handler.createChurch
    events:
      - http:
          path: churches
          method: post
          request:
            schemas:
              application/json: ${file(infraestructure/handlers/schemas/churches-schema.json)}

  updateChurch:
    handler: infraestructure/handlers/churches-handler.updateChurch
    events:
      - http:
          path: churches/{id}
          method: put
          request:
            schemas:
              application/json: ${file(infraestructure/handlers/schemas/churches-schema.json)}
  deleteChurch:
    handler: infraestructure/handlers/churches-handler.deleteChurch
    events:
      - http:
          path: churches/{id}
          method: delete  
  getDetailChurch:
    handler: infraestructure/handlers/churches-handler.getDetailChurch
    events:
      - http:
          path: churches/{id}
          method: get